# Generated by Django 3.2.6 on 2021-08-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210827_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Sender',
            new_name='sender',
        ),
    ]
