# Generated by Django 3.2.6 on 2021-08-31 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_readmessage_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.message'),
        ),
    ]
