# Generated by Django 3.2.6 on 2021-08-31 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210901_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='readmessage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
