# Generated by Django 3.2.6 on 2021-09-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_readmessage_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_message',
        ),
    ]
