# Generated by Django 3.2.6 on 2021-09-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_message_read_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.message'),
        ),
    ]
