# Generated by Django 3.2.6 on 2021-09-12 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210912_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
